spring.application.name=fitness-center-sys-test1
fitzone.data.members-file=Project 2/src/main/resources/data/members.txt
fitzone.data.payments-file=Project 2/src/main/resources/data/payments.txt
fitzone.data.trainers-file=Project 2/src/main/resources/data/trainers.txt
fitzone.data.membership-plans-file=Project 2/src/main/resources/data/membership_plans.txt
fitzone.data.workout-schedules-file=Project 2/src/main/resources/data/workout_schedules.txt
fitzone.data.diet-plans-file=Project 2/src/main/resources/data/diet_plans.txt